Post_management/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Post_management.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> dbContextOptions) : base(dbContextOptions)
        {

        }

        public DbSet<Categories> Category { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Tags> Tag { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Categories>().HasData(new Categories { Id = 1, Title = "Đời sống" });
            modelBuilder.Entity<Categories>().HasData(new Categories { Id = 2, Title = "Xã hội" });
            modelBuilder.Entity<Categories>().HasData(new Categories { Id = 3, Title = "Kinh tế" });

            modelBuilder.Entity<Post>().HasData(new Post
            {
                Id = 1,
                Title = "Codegym Huế",
                Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                CategoriesId = 1,
                TagsId = 1
            });
            modelBuilder.Entity<Post>().HasData(new Post
            {
                Id = 2,
                Title = "Nguyễn Tri Phương",
                Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                CategoriesId = 2,
                TagsId = 2
            });
            modelBuilder.Entity<Post>().HasData(new Post
            {
                Id = 3,
                Title = "Lễ Bế Giảng",
                Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                CategoriesId = 3,
                TagsId = 2
            });

            modelBuilder.Entity<Post_Tags>().HasKey(postTag => new { postTag.PostId, postTag.TagId });
            modelBuilder.Entity<Tags>().HasData(new Tags
            {
                Id = 1,
                Title = "Hot",
            });
            modelBuilder.Entity<Tags>().HasData(new Tags
            {
                Id = 2,
                Title = "News",
            });
            modelBuilder.Entity<Tags>().HasData(new Tags
            {
                Id = 3,
                Title = "Shock",
            });
        }
    }
}

Post_management/Models/Categories.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Post_management.Models
{
    public class Categories
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public List<Post> Posts { get; set; }
    }
}

Post_management/Models/ErrorViewModel.cs
using System;

namespace Post_management.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Post_management/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Post_management.Models
{
    public class Post
    {
        public int Id { get; set; }

        [DisplayName("Tên Tiêu Đề")]
        public string Title { get; set; }

        [DisplayName("Nội Dung")]
        public string Content { get; set; }

        [DisplayName("Thể Loại")]
        public int CategoriesId { get; set; }
        public Categories Category { get; set; }

        [DisplayName("Tags")]
        public int TagsId { get; set; }
        public Tags Tag { get; set; }
        public List<Post_Tags> Post_Tags { get; set; } = new List<Post_Tags>();
    }
}

Post_management/Models/Post_Tags.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Post_management.Models
{
    public class Post_Tags
    {
        public int PostId { get; set; }
        public int TagId { get; set; }
        public Post Post { get; set; }
        public Tags Tags { get; set; }
    }
}

Post_management/Models/Tags.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Post_management.Models
{
    public class Tags
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public List<Post_Tags> Post_Tag { get; set; }
        public List<Post> Posts { get; set; }
    }
}

Post_management/ViewModels/PostCreateVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Post_management.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Post_management.ViewModels
{
    public class PostCreateVM
    {
        public Post Posts { get; set; }

        public IEnumerable<Categories> Category { get; set; }
        public IEnumerable<SelectListItem> CategoriesSelectList { get; set; }
        public IEnumerable<Tags> Tag { get; set; }
        public IEnumerable<SelectListItem> TagsSelectList { get; set; }
    }
}

Post_management/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Post_management.Models;

namespace Post_management.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Post_management/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Post_management.Models;
using Post_management.ViewModels;

namespace Post_management.Controllers
{
    public class PostController : Controller
    {
        private readonly AppDbContext _appDbContext;
        public PostController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<Post> post = _appDbContext.Posts;
            return View(post);
        }
        public IActionResult Create()
        {
            PostCreateVM postCreateVM = new PostCreateVM()
            {
                Posts = new Post(),
                CategoriesSelectList = _appDbContext.Category.Select(item => new SelectListItem
                {
                    Text = item.Title,
                    Value = item.Id.ToString()
                }),
                TagsSelectList = _appDbContext.Tag.Select(item => new SelectListItem
                {
                    Text = item.Title,
                    Value = item.Id.ToString()
                })
            };

            return View(postCreateVM);
        }
        [HttpPost]
        public IActionResult Create(PostCreateVM postCreateVM)
        {
            _appDbContext.Posts.Add(postCreateVM.Posts);
            _appDbContext.SaveChanges();
            return View(postCreateVM);
        }
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Post_management/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Post_management/Views/Post/Create.cshtml
@model Post_management.ViewModels.PostCreateVM

<form method="post" enctype="multipart/form-data" asp-action="Create">
    <div class="border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info">Add Post</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="row form-group">
                    <div class="col-4">
                        <label asp-for="Posts.Title"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Posts.Title" class="form-control" />
                        <span asp-validation-for="Posts.Title" class="text-danger"></span>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-4">
                        <label asp-for="Posts.Content"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Posts.Content" class="form-control" />
                        <span asp-validation-for="Posts.Content" class="text-danger"></span>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-4">
                        <label asp-for="Posts.CategoriesId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Posts.CategoriesId" asp-items="@Model.CategoriesSelectList" class="form-control">
                            <option disabled selected>Vui lòng chọn Category</option>
                        </select>
                        <span asp-validation-for="Posts.CategoriesId" class="text-danger"></span>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-4">
                        <label asp-for="Posts.TagsId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Posts.TagsId" asp-items="@Model.TagsSelectList" class="form-control">
                            <option disabled selected>Vui lòng chọn Tags</option>
                        </select>
                        <span asp-validation-for="Posts.TagsId" class="text-danger"></span>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col">
                        <input type="submit" value="Create" class="btn btn-info" onclick="return validateInput()" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

Post_management/Views/Post/Index.cshtml
@model IEnumerable<Post>

<div>
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Post List</h2>
        </div>

        <div class="col-6">
            <a asp-controller="Post" asp-action="Create" class="btn btn-primary">
                Create New Post
            </a>
        </div>
    </div>

    @if (Model.Count() > 0)
    {
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Title
            </th>
            <th>
                Contents
            </th>
            <th>
                Categories
            </th>
            <th>
                Tags
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var post in Model)
        {
<tr>
    <td width="20%">
        @post.Id
    </td>
    <td width="20%">
        @post.Title
    </td>
    <td width="30%">
        @post.Content
    </td>
    <td width="15%">
        @post.CategoriesId
    </td>
    <td width="15%">
        @post.TagsId
    </td>
    <td>
        <div>
            <a asp-controller="Infor" asp-action="Edit" asp-route-Id="@post.Id" class="btn btn-primary"><i class="fas fa-edit"></i></a>
            <a asp-controller="Infor" asp-action="Delete" asp-route-Id="@post.Id" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
        </div>
    </td>
</tr>
}
    </tbody>
</table> }
else
{
<p>Không tồn tại liên lạc trong database</p>}


</div>

Post_management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Post_management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Post_management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">POST</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Post_management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>